name: build image
concurrency:
    cancel-in-progress: true
    group: ${{ github.workflow }}-${{ github.ref }}

on:
    pull_request:
        branches:
            - main

    push:
        branches:
            - main

    schedule:
        - cron: "0 7 * * *"

permissions:
    contents: read

env:
    IMAGE_NAME: "ghcr.io/prvious/frankenphp"
    REFRESH: ${{ github.event_name == 'schedule' && github.run_id || '' }}
    SHA: ${{ github.sha }}

jobs:
    prepare:
        runs-on: ubuntu-24.04
        outputs:
            variants: ${{ steps.matrix.outputs.variants }}
            platforms: ${{ steps.matrix.outputs.platforms }}
            metadata: ${{ steps.matrix.outputs.metadata }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Create variants matrix
              id: matrix
              shell: bash
              run: |
                  set -e
                  METADATA="$(docker buildx bake --print | jq -c)"
                  {
                    echo metadata="${METADATA}"
                    echo variants="$(jq -c '[.target | keys[] | select(startswith("runner-")) | sub("^runner-"; "")] | unique' <<< "${METADATA}")"
                    echo platforms="$(jq -c 'first(.target[]) | .platforms' <<< "${METADATA}")"
                  } >> "${GITHUB_OUTPUT}"

    build:
        runs-on: ${{ startsWith(matrix.platform, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
        needs:
            - prepare
        permissions:
            contents: read
            packages: write
        strategy:
            fail-fast: false
            matrix:
                variant: ${{ fromJson(needs.prepare.outputs.variants) }}
                platform: ${{ fromJson(needs.prepare.outputs.platforms) }}
        steps:
            - name: Prepare
              id: prepare
              run: |
                  platform=${{ matrix.platform }}
                  echo "sanitized_platform=${platform//\//-}" >> "${GITHUB_OUTPUT}"

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  platforms: ${{ matrix.platform }}

            - name: Login to ghcr.io
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Create tarball directory
              run: mkdir -p /tmp/images

            - name: Build
              id: build
              uses: docker/bake-action@v6
              with:
                  push: ${{ github.event_name != 'pull_request' }}
                  targets: runner-${{ matrix.variant }}
                  set: |
                      *.tags=
                      *.platform=${{ matrix.platform }}
                      *.cache-from=type=gha,scope=${{ matrix.variant }}-${{ github.ref }}-${{ matrix.platform }}
                      *.cache-from=type=gha,scope=${{ matrix.variant }}-${{ github.ref }}
                      *.cache-from=type=gha,scope=${{ matrix.variant }}-refs/heads/main-${{ matrix.platform }}
                      *.cache-from=type=gha,scope=${{ matrix.variant }}-refs/heads/main
                      *.cache-from=type=gha,scope=${{ matrix.variant }}-${{ matrix.platform }}
                      *.cache-from=type=gha,scope=${{ matrix.variant }}
                      *.cache-from=type=gha,scope=base-${{ matrix.platform }}
                      *.cache-from=type=gha,scope=base
                      *.cache-to=type=gha,scope=${{ matrix.variant }}-${{ github.ref }}-${{ matrix.platform }},mode=max,ignore-error=true
                      *.cache-to=type=gha,scope=${{ matrix.variant }}-${{ github.ref }},mode=max,ignore-error=true
                      *.cache-to=type=gha,scope=base-${{ matrix.platform }},mode=max,ignore-error=true
                      *.cache-to=type=gha,scope=base,mode=max,ignore-error=true
                      *.output=type=docker,name=frankenphp:test,dest=/tmp/images/runner-${{ matrix.variant }}-${{ steps.prepare.outputs.sanitized_platform }}.tar
                      ${{ github.event_name != 'pull_request' && format('*.output=type=image,name={0},push-by-digest=true,name-canonical=true,push=true', env.IMAGE_NAME) || '' }}

            - name: Upload image artifact
              uses: actions/upload-artifact@v4
              with:
                  name: image-runner-${{ matrix.variant }}-${{ steps.prepare.outputs.sanitized_platform }}
                  path: /tmp/images/runner-${{ matrix.variant }}-${{ steps.prepare.outputs.sanitized_platform }}.tar
                  if-no-files-found: error
                  compression-level: 0
                  retention-days: 1

            - # Workaround for https://github.com/actions/runner/pull/2477#issuecomment-1501003600
              name: Export metadata
              if: github.event_name != 'pull_request'
              run: |
                  mkdir -p /tmp/metadata/runner
                  runnerDigest=$(jq -r '."runner-${{ matrix.variant }}"."containerimage.digest"' <<< "${METADATA}")
                  touch "/tmp/metadata/runner/${runnerDigest#sha256:}"
              env:
                  METADATA: ${{ steps.build.outputs.metadata }}

            - name: Upload runner metadata
              if: github.event_name != 'pull_request'
              uses: actions/upload-artifact@v4
              with:
                  name: metadata-runner-${{ matrix.variant }}-${{ steps.prepare.outputs.sanitized_platform }}
                  path: /tmp/metadata/runner/*
                  if-no-files-found: error
                  retention-days: 1

    test:
        runs-on: ${{ startsWith(matrix.platform, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
        needs:
            - prepare
            - build
        strategy:
            fail-fast: false
            matrix:
                variant: ${{ fromJson(needs.prepare.outputs.variants) }}
                platform: ${{ fromJson(needs.prepare.outputs.platforms) }}
        steps:
            - name: Prepare
              id: prepare
              run: |
                  platform=${{ matrix.platform }}
                  echo "sanitized_platform=${platform//\//-}" >> "${GITHUB_OUTPUT}"

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download built image
              uses: actions/download-artifact@v4
              with:
                  name: image-runner-${{ matrix.variant }}-${{ steps.prepare.outputs.sanitized_platform }}
                  path: /tmp/images

            - name: Load image from tarball
              run: docker load --input "/tmp/images/runner-${{ matrix.variant }}-${{ steps.prepare.outputs.sanitized_platform }}.tar"

            - name: Test image environment
              run: |
                  # Get the built image name
                  case "${{ matrix.variant }}" in
                      *-dev) ENV_TYPE="dev" ;;
                      *) ENV_TYPE="production" ;;
                  esac

                  echo "🧪 Testing ${ENV_TYPE} environment"
                  docker run --rm -v "$PWD/test.php:/test.php:ro" -e FORCE_COLOR=1 frankenphp:test php /test.php "${ENV_TYPE}"

    push:
        runs-on: ubuntu-24.04
        needs:
            - prepare
            - build
            - test
        if: github.event_name != 'pull_request'
        permissions:
            contents: read
            packages: write
        strategy:
            fail-fast: false
            matrix:
                variant: ${{ fromJson(needs.prepare.outputs.variants) }}
        steps:
            - name: Download metadata
              uses: actions/download-artifact@v4
              with:
                  pattern: metadata-runner-${{ matrix.variant }}-*
                  path: /tmp/metadata
                  merge-multiple: true

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Create manifest list and push
              working-directory: /tmp/metadata
              run: |
                  set -x
                  # shellcheck disable=SC2046,SC2086
                  docker buildx imagetools create $(jq -cr '.target."runner-${{ matrix.variant }}".tags | map("-t " + .) | join(" ")' <<< "${METADATA}") \
                    $(printf "${IMAGE_NAME}@sha256:%s " *)
              env:
                  METADATA: ${{ needs.prepare.outputs.metadata }}

            - name: Inspect image
              run: |
                  # shellcheck disable=SC2046,SC2086
                  docker buildx imagetools inspect $(jq -cr '.target."runner-${{ matrix.variant }}".tags | first' <<< "${METADATA}")
              env:
                  METADATA: ${{ needs.prepare.outputs.metadata }}
